
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    pt: {
        // Header
        'header.features': 'Features',
        'header.pricing': 'Planos',
        'header.faq': 'FAQ',
        'header.login': 'Login',
        'header.start_free': 'Começar Grátis',

        // Hero
        'hero.badge': 'Powered by RAG + Embeddings',
        'hero.title': 'Centralize o raciocínio',
        'hero.title_highlight': 'arquitetural',
        'hero.title_end': 'da sua equipe',
        'hero.subtitle': 'ArchWeave conecta decisões de arquitetura (RFCs, ADRs) com problemas, soluções e código através de IA contextualizada. Para equipes que precisam documentar melhor e decidir mais rápido.',
        'hero.cta_primary': 'Comece Grátis Agora',
        'hero.cta_secondary': 'Agendar Demo',
        'hero.benefit_1': 'Grátis para começar',
        'hero.benefit_2': 'Sem cartão de crédito',
        'hero.benefit_3': 'Setup em 5 minutos',

        // Target audience
        'audience.title': 'Ideal para equipes que documentam pouco',
        'audience.subtitle': 'Plataforma pensada para ambientes distribuídos e squads autônomos que precisam alinhar decisões arquiteturais',
        'audience.architects': 'Arquitetos de Software',
        'audience.architects_desc': 'Centralize e versione suas decisões técnicas',
        'audience.teams': 'Times de Engenharia',
        'audience.teams_desc': 'Acesse contexto arquitetural rapidamente',
        'audience.leaders': 'Líderes Técnicos',
        'audience.leaders_desc': 'Mantenha alinhamento entre squads',

        // Features
        'features.title': 'Features que aceleram decisões arquiteturais',
        'features.subtitle': 'Tudo que você precisa para documentar, buscar e reutilizar conhecimento arquitetural',
        'features.editor.title': 'Editor Markdown RFC/ADR',
        'features.editor.desc': 'Versão colaborativa com /comandos, mentions e custom blocks. Integração futura com GitHub.',
        'features.diagrams.title': 'Diagramas Interativos',
        'features.diagrams.desc': 'Diagramas C4, ERD, Sequence. Nodes customizáveis e plugins extensíveis.',
        'features.search.title': 'Busca Inteligente RAG',
        'features.search.desc': 'Respostas explicadas com links diretos a decisões. Ranking de similaridade.',
        'features.classification.title': 'Classificação MCP',
        'features.classification.desc': 'Classifica problemas e propõe padrões aderentes ao contexto arquitetural.',
        'features.database.title': 'Base Unificada',
        'features.database.desc': 'Repositório versionado de decisões, problemas e alternativas com tags e relacionamentos.',
        'features.api.title': 'API + Webhooks + SDK',
        'features.api.desc': 'Use como backend de arquitetura para integrações com suas ferramentas existentes.',

        // How it works
        'how_it_works.title': 'Como Funciona',
        'how_it_works.subtitle': 'Do problema à decisão em 4 passos simples',
        'how_it_works.step1.title': 'Identifique o Problema',
        'how_it_works.step1.desc': 'Documente o contexto e limitações',
        'how_it_works.step2.title': 'Busque Soluções',
        'how_it_works.step2.desc': 'IA sugere padrões e decisões similares',
        'how_it_works.step3.title': 'Documente RFC/ADR',
        'how_it_works.step3.desc': 'Editor colaborativo com templates',
        'how_it_works.step4.title': 'Reutilize Conhecimento',
        'how_it_works.step4.desc': 'Busca semântica para contextos futuros',

        // Testimonials
        'testimonials.title': 'O que dizem as equipes',
        'testimonials.quote1': 'Reduzimos 70% dos debates redundantes com decisões versionadas em um só lugar',
        'testimonials.author1': 'João Silva',
        'testimonials.role1': 'Lead Architect, TechCorp',
        'testimonials.quote2': 'A busca inteligente nos economiza horas procurando por decisões passadas',
        'testimonials.author2': 'Maria Santos',
        'testimonials.role2': 'Engineering Manager, StartupXYZ',

        // Pricing
        'pricing.title': 'Planos para toda equipe',
        'pricing.subtitle': 'Comece grátis e escale conforme sua necessidade',
        'pricing.free.name': 'Grátis',
        'pricing.free.price': 'R$0',
        'pricing.free.period': 'para sempre',
        'pricing.free.feature1': '1 colaborador',
        'pricing.free.feature2': 'Até 30 RFCs e ADRs',
        'pricing.free.feature3': 'Diagramação básica',
        'pricing.free.feature4': 'Suporte comunidade',
        'pricing.free.button': 'Começar Grátis',
        'pricing.pro.name': 'Pro',
        'pricing.pro.price': 'R$49',
        'pricing.pro.period': '/mês',
        'pricing.pro.feature1': 'Até 10 colaboradores',
        'pricing.pro.feature2': 'RFCs e ADRs ilimitados',
        'pricing.pro.feature3': 'Diagramação avançada',
        'pricing.pro.feature4': 'RAG + Embeddings',
        'pricing.pro.feature5': 'Integrações Git',
        'pricing.pro.feature6': 'Suporte por email',
        'pricing.pro.button': 'Começar Teste',
        'pricing.enterprise.name': 'Enterprise',
        'pricing.enterprise.price': 'Sob consulta',
        'pricing.enterprise.period': '',
        'pricing.enterprise.feature1': 'Colaboradores ilimitados',
        'pricing.enterprise.feature2': 'Fine-tuning dedicado',
        'pricing.enterprise.feature3': 'Integrações Git avançadas',
        'pricing.enterprise.feature4': 'SSO / RBAC',
        'pricing.enterprise.feature5': 'Suporte dedicado',
        'pricing.enterprise.button': 'Falar com Vendas',
        'pricing.popular': 'Mais Popular',

        // FAQ
        'faq.title': 'Perguntas Frequentes',
        'faq.q1': 'Como integro com meu Git?',
        'faq.a1': 'Oferecemos webhooks e API para sincronizar automaticamente com GitHub, GitLab e outros repositórios.',
        'faq.q2': 'Preciso treinar um modelo?',
        'faq.a2': 'Não! Usamos modelos pré-treinados que funcionam out-of-the-box. No plano Enterprise, oferecemos fine-tuning dedicado.',
        'faq.q3': 'Como exporto os documentos?',
        'faq.a3': 'Exportação em Markdown, PDF e HTML. API para integrações personalizadas com suas ferramentas.',
        'faq.q4': 'O que é RAG e como ele ajuda?',
        'faq.a4': 'RAG (Retrieval-Augmented Generation) combina busca semântica com IA generativa para fornecer respostas contextualizadas baseadas em suas decisões arquiteturais.',

        // CTA
        'cta.title': 'Pronto para centralizar suas decisões arquiteturais?',
        'cta.subtitle': 'Junte-se a centenas de arquitetos que já usam ArchWeave para documentar e reutilizar conhecimento técnico.',
        'cta.button_primary': 'Começar Grátis',
        'cta.button_secondary': 'Agendar Demo',

        // Footer
        'footer.tagline': 'Centralize o raciocínio arquitetural da sua equipe.',
        'footer.product': 'Produto',
        'footer.features': 'Features',
        'footer.plans': 'Planos',
        'footer.roadmap': 'Roadmap',
        'footer.resources': 'Recursos',
        'footer.documentation': 'Documentação',
        'footer.templates': 'Templates',
        'footer.blog': 'Blog',
        'footer.support': 'Suporte',
        'footer.help_center': 'Help Center',
        'footer.community': 'Comunidade',
        'footer.contact': 'Contato',
        'footer.privacy': 'Privacidade',
        'footer.terms': 'Termos',
        'footer.rights': '© 2024 ArchWeave. Todos os direitos reservados.',
        'footer.fixed_cta': 'Testar Demo',

        // Documentation specific translations
        'docs.sidebar.introduction': 'Introdução',
        'docs.sidebar.getting_started': 'Primeiros Passos',
        'docs.sidebar.features': 'Funcionalidades',
        'docs.sidebar.tutorials': 'Tutoriais',
        'docs.sidebar.api_reference': 'Referência da API',
        'docs.sidebar.examples': 'Exemplos',
        'docs.search_placeholder': 'Buscar documentação...',
        'docs.header.try_now': 'Experimente Agora',
        'docs.welcome.badge': 'Documentação',
        'docs.welcome.title': 'Bem-vindo',
        'docs.welcome.subtitle': 'Aprenda sobre o ArchWeave e como começar',
        'docs.welcome.video_title': 'ArchWeave 2.0 chegou. Codificação colaborativa. Mais inteligente &...',
        'docs.welcome.video_desc': 'Assista nosso vídeo de introdução para entender os conceitos principais',
        'docs.welcome.watch_video': 'Assistir no YouTube',
        'docs.welcome.description': 'ArchWeave é uma plataforma alimentada por IA que permite usuários de qualquer nível de habilidade criar documentação de arquitetura full-stack através de linguagem natural. Simplesmente descreva o que você quer, e o ArchWeave constrói para você.',
        'docs.quick_start.title': 'Início Rápido',
        'docs.quick_start.getting_started.title': 'Primeiros Passos',
        'docs.quick_start.getting_started.desc': 'Tutorial passo a passo para criar seu primeiro projeto.',
        'docs.quick_start.features.title': 'Funcionalidades',
        'docs.quick_start.features.desc': 'Funcionalidades principais do ArchWeave.',
        'docs.quick_start.integrations.title': 'Integrações',
        'docs.quick_start.integrations.desc': 'Estenda funcionalidades com integrações.',
        'docs.learn_more': 'Saiba mais',
        'docs.features.title': 'Funcionalidades Principais',
        'docs.features.editor.title': 'Editor Markdown + Diagramas',
        'docs.features.editor.desc': 'Edição de texto rico com capacidades de diagramação integradas',
        'docs.features.editor.item1': 'Visualização ao vivo com destaque de sintaxe',
        'docs.features.editor.item2': 'Criação de diagramas por arrastar e soltar',
        'docs.features.editor.item3': 'Exportação para múltiplos formatos',
        'docs.features.diagrams.title': 'Suporte Avançado a Diagramas',
        'docs.features.diagrams.desc': 'Múltiplos tipos de diagramas para diferentes necessidades arquiteturais',
        'docs.features.diagrams.item1': 'Diagramas Entidade-Relacionamento (ER)',
        'docs.features.diagrams.item2': 'Diagramas de workflow e processo',
        'docs.features.diagrams.item3': 'Integração C4 e Mermaid',
        'docs.features.ai.title': 'Sistema RAG Alimentado por IA',
        'docs.features.ai.desc': 'Assistência de IA contextual para decisões arquiteturais',
        'docs.features.ai.item1': 'Interface estilo ChatGPT para consultas',
        'docs.features.ai.item2': 'Base de conhecimento ADR e RFC',
        'docs.features.ai.item3': 'Geração automática de documentação',
        'docs.tutorials.title': 'Tutoriais em Vídeo',
        'docs.tutorials.first_project.title': 'Crie Seu Primeiro Projeto',
        'docs.tutorials.first_project.desc': 'Aprenda o básico de criar e gerenciar projetos',
        'docs.tutorials.first_project.duration': '10 min',
        'docs.tutorials.advanced_diagrams.title': 'Diagramação Avançada',
        'docs.tutorials.advanced_diagrams.desc': 'Domine a criação e customização de diagramas complexos',
        'docs.tutorials.advanced_diagrams.duration': '15 min',
        'docs.tutorials.ai_integration.title': 'Guia de Integração IA',
        'docs.tutorials.ai_integration.desc': 'Aproveite a IA para suporte a decisões arquiteturais',
        'docs.tutorials.ai_integration.duration': '20 min',
        'docs.tutorials.team_collaboration.title': 'Colaboração em Equipe',
        'docs.tutorials.team_collaboration.desc': 'Configure workspaces para colaboração em equipe',
        'docs.tutorials.team_collaboration.duration': '12 min',
        'docs.tutorials.beginner': 'Iniciante',
        'docs.tutorials.intermediate': 'Intermediário',
        'docs.tutorials.advanced': 'Avançado',
        'docs.cta.title': 'Pronto para começar?',
        'docs.cta.subtitle': 'Junte-se a milhares de arquitetos e equipes de engenharia que já usam o ArchWeave para documentar e manter sua arquitetura de software.',
        'docs.cta.start_now': 'Começar Agora',
        'docs.cta.join_waitlist': 'Entrar na Lista',

        // DocsApp specific translations
        'docs_app.header.docs': 'Docs',
        'docs_app.header.try_now': 'Experimente Agora',
        'docs_app.search_placeholder': 'Buscar docs...',
        'docs_app.sidebar.getting_started': 'Primeiros Passos',
        'docs_app.sidebar.overview': 'Visão Geral',
        'docs_app.sidebar.installation': 'Instalação',
        'docs_app.sidebar.quick_start': 'Início Rápido',
        'docs_app.sidebar.features': 'Funcionalidades',
        'docs_app.sidebar.markdown_editor': 'Editor Markdown',
        'docs_app.sidebar.erd_diagrams': 'Diagramas ER',
        'docs_app.sidebar.workflow_diagrams': 'Diagramas de Workflow',
        'docs_app.sidebar.ai_rag': 'IA & RAG',
        'docs_app.sidebar.search': 'Busca',
        'docs_app.sidebar.guides': 'Guias',
        'docs_app.sidebar.chat_assistant': 'Assistente de Chat',
        'docs_app.sidebar.project_management': 'Gestão de Projetos',
        'docs_app.sidebar.api_reference': 'Referência da API',
        'docs_app.overview.badge': 'Documentação',
        'docs_app.overview.title': 'Documentação ArchWeave',
        'docs_app.overview.subtitle': 'Guia completo para usar o ArchWeave na documentação de arquitetura de software e gestão de conhecimento com RAG.',
        'docs_app.overview.welcome_title': 'Bem-vindo ao ArchWeave',
        'docs_app.overview.welcome_desc': 'O ArchWeave te ajuda a criar, visualizar e interagir com sua arquitetura de software através de documentação alimentada por IA e recuperação inteligente de conhecimento.',
        'docs_app.overview.get_started': 'Começar',
        'docs_app.overview.try_demo': 'Ver Demo',
        'docs_app.features.title': 'Funcionalidades Principais',
        'docs_app.features.markdown.title': 'Editor Markdown',
        'docs_app.features.markdown.desc': 'Editor de texto rico com preview ao vivo e integração de diagramas',
        'docs_app.features.erd.title': 'Diagramas ER',
        'docs_app.features.erd.desc': 'Crie e edite diagramas entidade-relacionamento visualmente',
        'docs_app.features.workflow.title': 'Diagramas de Workflow',
        'docs_app.features.workflow.desc': 'Projete fluxos de processo e workflows arquiteturais',
        'docs_app.features.ai.title': 'IA & RAG',
        'docs_app.features.ai.desc': 'Assistência de IA contextual para decisões arquiteturais',
        'docs_app.features.search.title': 'Busca Inteligente',
        'docs_app.features.search.desc': 'Busca semântica em todo seu conhecimento arquitetural',
        'docs_app.features.chat.title': 'Assistente de Chat',
        'docs_app.features.chat.desc': 'Interface estilo ChatGPT para consultar sua arquitetura',
        'docs_app.learn_more': 'Saiba mais',
        'docs_app.quick_links.title': 'Links Rápidos',
        'docs_app.quick_links.quick_start.title': 'Guia de Início Rápido',
        'docs_app.quick_links.quick_start.desc': 'Configure e execute o ArchWeave em minutos',
        'docs_app.quick_links.quick_start.button': 'Iniciar Tutorial',
        'docs_app.quick_links.examples.title': 'Exemplos Ao Vivo',
        'docs_app.quick_links.examples.desc': 'Explore exemplos interativos e templates',
        'docs_app.quick_links.examples.button': 'Ver Exemplos',
        'docs_app.installation.title': 'Instalação',
        'docs_app.installation.npm_install': 'Instalar com npm',
        'docs_app.installation.copy': 'Copiar',
        'docs_app.installation.feature1': 'Suporte TypeScript incluído',
        'docs_app.installation.feature2': 'Nenhuma configuração adicional necessária',
        'docs_app.installation.feature3': 'Funciona com projetos React existentes',
        'docs_app.cta.title': 'Pronto para criar docs de arquitetura melhores?',
        'docs_app.cta.subtitle': 'Junte-se à comunidade de arquitetos e engenheiros usando ArchWeave para transformar seu fluxo de documentação.',
        'docs_app.cta.get_started': 'Começar',
        'docs_app.cta.try_demo': 'Ver Demo',

        // Waitlist
        'waitlist.nav.features': 'Features',
        'waitlist.nav.benefits': 'Benefícios',
        'waitlist.nav.join': 'Entrar na Lista',
        'waitlist.badge': 'Acesso Antecipado',
        'waitlist.hero.title': 'Documente, visualize e converse',
        'waitlist.hero.title_highlight': 'com sua arquitetura',
        'waitlist.hero.subtitle': 'Uma plataforma que integra geração de conhecimento arquitetural com inteligência artificial, permitindo criar, consultar e manter documentação viva da sua arquitetura de software.',
        'waitlist.email.placeholder': 'Digite seu endereço de email',
        'waitlist.email.button': 'Entrar na Lista de Espera',
        'waitlist.success.title': 'Você está na lista!',
        'waitlist.success.subtitle': 'Enviaremos atualizações e acesso antecipado quando lançarmos.',
        'waitlist.benefits.early': 'Acesso Antecipado',
        'waitlist.benefits.free': 'Grátis para Participar',
        'waitlist.benefits.shape': 'Molde o Produto',
        'waitlist.features.title': 'Funcionalidades Principais',
        'waitlist.features.subtitle': 'Ferramentas poderosas para arquitetos de software, tech leads e times de engenharia',
        'waitlist.feature.editor.title': 'Editor Markdown + Diagramas',
        'waitlist.feature.editor.desc': 'Editor colaborativo com suporte a diagramas integrados e documentação arquitetural rica',
        'waitlist.feature.erd.title': 'Diagramas ER Avançados',
        'waitlist.feature.erd.desc': 'Crie diagramas de entidade-relacionamento com ReactFlow customizado e interações inteligentes',
        'waitlist.feature.workflow.title': 'Diagramas de Workflow',
        'waitlist.feature.workflow.desc': 'Visualize fluxos de processo e decisões arquiteturais com diagramas C4, Mermaid e mais',
        'waitlist.feature.ai.title': 'IA Contextual (RAG)',
        'waitlist.feature.ai.desc': 'Chat estilo ChatGPT que responde sobre suas decisões arquiteturais, ADRs, RFCs e histórico de projetos',
        'waitlist.feature.search.title': 'Busca Global Inteligente',
        'waitlist.feature.search.desc': 'Encontre qualquer informação arquitetural com busca semântica baseada em embeddings',
        'waitlist.feature.workspace.title': 'Workspaces Modulares',
        'waitlist.feature.workspace.desc': 'Organize projetos com estrutura modular',
        'waitlist.audience.title': 'Ideal para quem preza governança arquitetural',
        'waitlist.audience.subtitle': 'Plataforma pensada para profissionais e empresas que precisam documentar e manter decisões arquiteturais',
        'waitlist.audience.architects': 'Arquitetos de Software',
        'waitlist.audience.architects_desc': 'Centralize e versione suas decisões técnicas com IA',
        'waitlist.audience.leads': 'Tech Leads',
        'waitlist.audience.leads_desc': 'Mantenha documentação viva e acessível para a equipe',
        'waitlist.audience.teams': 'Times de Engenharia',
        'waitlist.audience.teams_desc': 'Acesse contexto arquitetural e histórico de decisões rapidamente',
        'waitlist.benefits.title': 'Por que Participar do Acesso Antecipado?',
        'waitlist.benefits.subtitle': 'Seja pioneiro na evolução da documentação arquitetural',
        'waitlist.benefit.early.title': 'Acesso Exclusivo',
        'waitlist.benefit.early.desc': 'Seja o primeiro a usar nossa plataforma de RAG para arquitetura antes do lançamento público',
        'waitlist.benefit.shape.title': 'Influencie o Desenvolvimento',
        'waitlist.benefit.shape.desc': 'Seu feedback moldará as funcionalidades e a experiência da plataforma',
        'waitlist.benefit.free.title': 'Beta Gratuito',
        'waitlist.benefit.free.desc': 'Acesso completo durante o período beta sem custos para early adopters',
        'waitlist.suggestions.title': 'Compartilhe suas Necessidades',
        'waitlist.suggestions.subtitle': 'Conte-nos sobre seus desafios atuais com documentação arquitetural e governança',
        'waitlist.suggestions.label': 'Que desafios você enfrenta na documentação da sua arquitetura?',
        'waitlist.suggestions.placeholder': 'Ex: Dificuldade em manter ADRs atualizados, falta de visibilidade das decisões arquiteturais, necessidade de consultar histórico de mudanças...',
        'waitlist.suggestions.button': 'Enviar Feedback',
        'waitlist.suggestions.success': 'Obrigado!',
        'waitlist.suggestions.success_desc': 'Seu feedback nos ajudará a priorizar funcionalidades',
        'waitlist.cta.title': 'Pronto para Revolucionar sua Governança Arquitetural?',
        'waitlist.cta.subtitle': 'Junte-se a arquitetos e tech leads que estão esperando pela nova era da documentação arquitetural inteligente',
        'waitlist.cta.button': 'Garantir Acesso Antecipado',
        'waitlist.footer.tagline': 'Documente, visualize e converse com sua arquitetura',
        'waitlist.toast.email_required': 'Email obrigatório',
        'waitlist.toast.email_required_desc': 'Por favor, digite seu endereço de email',
        'waitlist.toast.welcome': 'Bem-vindo à lista de espera!',
        'waitlist.toast.welcome_desc': 'Notificaremos você quando o acesso antecipado estiver disponível',
    },
    en: {
        // Header
        'header.features': 'Features',
        'header.pricing': 'Pricing',
        'header.faq': 'FAQ',
        'header.login': 'Login',
        'header.start_free': 'Start Free',

        // Hero
        'hero.badge': 'Powered by RAG + Embeddings',
        'hero.title': 'Centralize your team\'s',
        'hero.title_highlight': 'architectural',
        'hero.title_end': 'reasoning',
        'hero.subtitle': 'ArchWeave connects architecture decisions (RFCs, ADRs) with problems, solutions and code through contextualized AI. For teams that need to document better and decide faster.',
        'hero.cta_primary': 'Start Free Now',
        'hero.cta_secondary': 'Schedule Demo',
        'hero.benefit_1': 'Free to start',
        'hero.benefit_2': 'No credit card',
        'hero.benefit_3': '5-minute setup',

        // Target audience
        'audience.title': 'Ideal for teams that document little',
        'audience.subtitle': 'Platform designed for distributed environments and autonomous squads that need to align architectural decisions',
        'audience.architects': 'Software Architects',
        'audience.architects_desc': 'Centralize and version your technical decisions',
        'audience.teams': 'Engineering Teams',
        'audience.teams_desc': 'Access architectural context quickly',
        'audience.leaders': 'Technical Leaders',
        'audience.leaders_desc': 'Maintain alignment between squads',

        // Features
        'features.title': 'Features that accelerate architectural decisions',
        'features.subtitle': 'Everything you need to document, search and reuse architectural knowledge',
        'features.editor.title': 'Markdown RFC/ADR Editor',
        'features.editor.desc': 'Collaborative version with /commands, mentions and custom blocks. Future GitHub integration.',
        'features.diagrams.title': 'Interactive Diagrams',
        'features.diagrams.desc': 'Diagrams C4, ERD, Sequence support. Customizable nodes and extensible plugins.',
        'features.search.title': 'Smart RAG Search',
        'features.search.desc': 'Explained answers with direct links to decisions. Similarity ranking.',
        'features.classification.title': 'MCP Classification',
        'features.classification.desc': 'Classifies problems and proposes patterns adherent to architectural context.',
        'features.database.title': 'Unified Base',
        'features.database.desc': 'Versioned repository of decisions, problems and alternatives with tags and relationships.',
        'features.api.title': 'API + Webhooks + SDK',
        'features.api.desc': 'Use as architecture backend for integrations with your existing tools.',

        // How it works
        'how_it_works.title': 'How It Works',
        'how_it_works.subtitle': 'From problem to decision in 4 simple steps',
        'how_it_works.step1.title': 'Identify the Problem',
        'how_it_works.step1.desc': 'Document context and constraints',
        'how_it_works.step2.title': 'Search Solutions',
        'how_it_works.step2.desc': 'AI suggests similar patterns and decisions',
        'how_it_works.step3.title': 'Document RFC/ADR',
        'how_it_works.step3.desc': 'Collaborative editor with templates',
        'how_it_works.step4.title': 'Reuse Knowledge',
        'how_it_works.step4.desc': 'Semantic search for future contexts',

        // Testimonials
        'testimonials.title': 'What teams are saying',
        'testimonials.quote1': 'We reduced 70% of redundant debates with versioned decisions in one place',
        'testimonials.author1': 'John Silva',
        'testimonials.role1': 'Lead Architect, TechCorp',
        'testimonials.quote2': 'Smart search saves us hours looking for past decisions',
        'testimonials.author2': 'Maria Santos',
        'testimonials.role2': 'Engineering Manager, StartupXYZ',

        // Pricing
        'pricing.title': 'Plans for every team',
        'pricing.subtitle': 'Start free and scale as needed',
        'pricing.free.name': 'Free',
        'pricing.free.price': '$0',
        'pricing.free.period': 'forever',
        'pricing.free.feature1': '1 collaborator',
        'pricing.free.feature2': 'Up to 30 RFCs and ADRs',
        'pricing.free.feature3': 'Basic diagramming',
        'pricing.free.feature4': 'Community support',
        'pricing.free.button': 'Start Free',
        'pricing.pro.name': 'Pro',
        'pricing.pro.price': '$29',
        'pricing.pro.period': '/month',
        'pricing.pro.feature1': 'Up to 10 collaborators',
        'pricing.pro.feature2': 'Unlimited RFCs and ADRs',
        'pricing.pro.feature3': 'Advanced diagramming',
        'pricing.pro.feature4': 'RAG + Embeddings',
        'pricing.pro.feature5': 'Git integrations',
        'pricing.pro.feature6': 'Email support',
        'pricing.pro.button': 'Start Trial',
        'pricing.enterprise.name': 'Enterprise',
        'pricing.enterprise.price': 'Custom',
        'pricing.enterprise.period': '',
        'pricing.enterprise.feature1': 'Unlimited collaborators',
        'pricing.enterprise.feature2': 'Dedicated fine-tuning',
        'pricing.enterprise.feature3': 'Advanced Git integrations',
        'pricing.enterprise.feature4': 'SSO / RBAC',
        'pricing.enterprise.feature5': 'Dedicated support',
        'pricing.enterprise.button': 'Contact Sales',
        'pricing.popular': 'Most Popular',

        // FAQ
        'faq.title': 'Frequently Asked Questions',
        'faq.q1': 'How do I integrate with my Git?',
        'faq.a1': 'We offer webhooks and API to automatically sync with GitHub, GitLab and other repositories.',
        'faq.q2': 'Do I need to train a model?',
        'faq.a2': 'No! We use pre-trained models that work out-of-the-box. In Enterprise plan, we offer dedicated fine-tuning.',
        'faq.q3': 'How do I export documents?',
        'faq.a3': 'Export in Markdown, PDF and HTML. API for custom integrations with your tools.',
        'faq.q4': 'What is RAG and how does it help?',
        'faq.a4': 'RAG (Retrieval-Augmented Generation) combines semantic search with generative AI to provide contextualized answers based on your architectural decisions.',

        // CTA
        'cta.title': 'Ready to centralize your architectural decisions?',
        'cta.subtitle': 'Join hundreds of architects already using ArchWeave to document and reuse technical knowledge.',
        'cta.button_primary': 'Start Free',
        'cta.button_secondary': 'Schedule Demo',

        // Footer
        'footer.tagline': 'Centralize your team\'s architectural reasoning.',
        'footer.product': 'Product',
        'footer.features': 'Features',
        'footer.plans': 'Plans',
        'footer.roadmap': 'Roadmap',
        'footer.resources': 'Resources',
        'footer.documentation': 'Documentation',
        'footer.templates': 'Templates',
        'footer.blog': 'Blog',
        'footer.support': 'Support',
        'footer.help_center': 'Help Center',
        'footer.community': 'Community',
        'footer.contact': 'Contact',
        'footer.privacy': 'Privacy',
        'footer.terms': 'Terms',
        'footer.rights': '© 2024 ArchWeave. All rights reserved.',
        'footer.fixed_cta': 'Test Demo',

        // Documentation specific translations
        'docs.sidebar.introduction': 'Introduction',
        'docs.sidebar.getting_started': 'Getting Started',
        'docs.sidebar.features': 'Features',
        'docs.sidebar.tutorials': 'Tutorials',
        'docs.sidebar.api_reference': 'API Reference',
        'docs.sidebar.examples': 'Examples',
        'docs.search_placeholder': 'Search documentation...',
        'docs.header.try_now': 'Try Now',
        'docs.welcome.badge': 'Documentation',
        'docs.welcome.title': 'Welcome',
        'docs.welcome.subtitle': 'Learn about ArchWeave and how to get started',
        'docs.welcome.video_title': 'ArchWeave 2.0 is here. Multiplayer vibe coding. Smarter &...',
        'docs.welcome.video_desc': 'Watch our introduction video to understand the core concepts',
        'docs.welcome.watch_video': 'Watch on YouTube',
        'docs.welcome.description': 'ArchWeave is an AI-powered platform that enables users of any skill level to create full-stack architecture documentation through natural language. Simply describe what you want, and ArchWeave builds it for you.',
        'docs.quick_start.title': 'Quick Start',
        'docs.quick_start.getting_started.title': 'Getting Started',
        'docs.quick_start.getting_started.desc': 'Step-by-step tutorial to create your first project.',
        'docs.quick_start.features.title': 'Features',
        'docs.quick_start.features.desc': "ArchWeave's core features.",
        'docs.quick_start.integrations.title': 'Integrations',
        'docs.quick_start.integrations.desc': 'Extend functionality with integrations.',
        'docs.learn_more': 'Learn more',
        'docs.features.title': 'Core Features',
        'docs.features.editor.title': 'Markdown Editor + Diagrams',
        'docs.features.editor.desc': 'Rich text editing with integrated diagramming capabilities',
        'docs.features.editor.item1': 'Live preview with syntax highlighting',
        'docs.features.editor.item2': 'Drag-and-drop diagram creation',
        'docs.features.editor.item3': 'Export to multiple formats',
        'docs.features.diagrams.title': 'Advanced Diagram Support',
        'docs.features.diagrams.desc': 'Multiple diagram types for different architectural needs',
        'docs.features.diagrams.item1': 'Entity-Relationship (ER) diagrams',
        'docs.features.diagrams.item2': 'Workflow and process diagrams',
        'docs.features.diagrams.item3': 'C4 and Mermaid integration',
        'docs.features.ai.title': 'AI-Powered RAG System',
        'docs.features.ai.desc': 'Contextual AI assistance for architectural decisions',
        'docs.features.ai.item1': 'ChatGPT-style interface for queries',
        'docs.features.ai.item2': 'ADR and RFC knowledge base',
        'docs.features.ai.item3': 'Automatic documentation generation',
        'docs.tutorials.title': 'Video Tutorials',
        'docs.tutorials.first_project.title': 'Create Your First Project',
        'docs.tutorials.first_project.desc': 'Learn the basics of creating and managing projects',
        'docs.tutorials.first_project.duration': '10 min',
        'docs.tutorials.advanced_diagrams.title': 'Advanced Diagramming',
        'docs.tutorials.advanced_diagrams.desc': 'Master complex diagram creation and customization',
        'docs.tutorials.advanced_diagrams.duration': '15 min',
        'docs.tutorials.ai_integration.title': 'AI Integration Guide',
        'docs.tutorials.ai_integration.desc': 'Leverage AI for architectural decision support',
        'docs.tutorials.ai_integration.duration': '20 min',
        'docs.tutorials.team_collaboration.title': 'Team Collaboration',
        'docs.tutorials.team_collaboration.desc': 'Set up workspaces for team collaboration',
        'docs.tutorials.team_collaboration.duration': '12 min',
        'docs.tutorials.beginner': 'Beginner',
        'docs.tutorials.intermediate': 'Intermediate',
        'docs.tutorials.advanced': 'Advanced',
        'docs.cta.title': 'Ready to get started?',
        'docs.cta.subtitle': 'Join thousands of architects and engineering teams already using ArchWeave to document and maintain their software architecture.',
        'docs.cta.start_now': 'Start Now',
        'docs.cta.join_waitlist': 'Join Waitlist',

        // DocsApp specific translations
        'docs_app.header.docs': 'Docs',
        'docs_app.header.try_now': 'Try Now',
        'docs_app.search_placeholder': 'Search docs...',
        'docs_app.sidebar.getting_started': 'Getting Started',
        'docs_app.sidebar.overview': 'Overview',
        'docs_app.sidebar.installation': 'Installation',
        'docs_app.sidebar.quick_start': 'Quick Start',
        'docs_app.sidebar.features': 'Features',
        'docs_app.sidebar.markdown_editor': 'Markdown Editor',
        'docs_app.sidebar.erd_diagrams': 'ER Diagrams',
        'docs_app.sidebar.workflow_diagrams': 'Workflow Diagrams',
        'docs_app.sidebar.ai_rag': 'AI & RAG',
        'docs_app.sidebar.search': 'Search',
        'docs_app.sidebar.guides': 'Guides',
        'docs_app.sidebar.chat_assistant': 'Chat Assistant',
        'docs_app.sidebar.project_management': 'Project Management',
        'docs_app.sidebar.api_reference': 'API Reference',
        'docs_app.overview.badge': 'Documentation',
        'docs_app.overview.title': 'ArchWeave Documentation',
        'docs_app.overview.subtitle': 'Complete guide to using ArchWeave for software architecture documentation and RAG-powered knowledge management.',
        'docs_app.overview.welcome_title': 'Welcome to ArchWeave',
        'docs_app.overview.welcome_desc': 'ArchWeave helps you create, visualize, and interact with your software architecture through AI-powered documentation and intelligent knowledge retrieval.',
        'docs_app.overview.get_started': 'Get Started',
        'docs_app.overview.try_demo': 'Try Demo',
        'docs_app.features.title': 'Core Features',
        'docs_app.features.markdown.title': 'Markdown Editor',
        'docs_app.features.markdown.desc': 'Rich text editor with live preview and diagram integration',
        'docs_app.features.erd.title': 'ER Diagrams',
        'docs_app.features.erd.desc': 'Create and edit entity-relationship diagrams visually',
        'docs_app.features.workflow.title': 'Workflow Diagrams',
        'docs_app.features.workflow.desc': 'Design process flows and architectural workflows',
        'docs_app.features.ai.title': 'AI & RAG',
        'docs_app.features.ai.desc': 'Contextual AI assistance for architectural decisions',
        'docs_app.features.search.title': 'Smart Search',
        'docs_app.features.search.desc': 'Semantic search across all your architectural knowledge',
        'docs_app.features.chat.title': 'Chat Assistant',
        'docs_app.features.chat.desc': 'ChatGPT-style interface for querying your architecture',
        'docs_app.learn_more': 'Learn more',
        'docs_app.quick_links.title': 'Quick Links',
        'docs_app.quick_links.quick_start.title': 'Quick Start Guide',
        'docs_app.quick_links.quick_start.desc': 'Get up and running with ArchWeave in minutes',
        'docs_app.quick_links.quick_start.button': 'Start Tutorial',
        'docs_app.quick_links.examples.title': 'Live Examples',
        'docs_app.quick_links.examples.desc': 'Explore interactive examples and templates',
        'docs_app.quick_links.examples.button': 'View Examples',
        'docs_app.installation.title': 'Installation',
        'docs_app.installation.npm_install': 'Install with npm',
        'docs_app.installation.copy': 'Copy',
        'docs_app.installation.feature1': 'TypeScript support included',
        'docs_app.installation.feature2': 'No additional configuration required',
        'docs_app.installation.feature3': 'Works with existing React projects',
        'docs_app.cta.title': 'Ready to build better architecture docs?',
        'docs_app.cta.subtitle': 'Join the community of architects and engineers using ArchWeave to transform their documentation workflow.',
        'docs_app.cta.get_started': 'Get Started',
        'docs_app.cta.try_demo': 'Try Demo',

        // Waitlist
        'waitlist.nav.features': 'Features',
        'waitlist.nav.benefits': 'Benefits',
        'waitlist.nav.join': 'Join Waitlist',
        'waitlist.badge': 'Early Access',
        'waitlist.hero.title': 'Document, visualize and talk',
        'waitlist.hero.title_highlight': 'with your architecture',
        'waitlist.hero.subtitle': 'A platform that integrates architectural knowledge generation with artificial intelligence, allowing you to create, query and maintain living documentation of your software architecture.',
        'waitlist.email.placeholder': 'Enter your email address',
        'waitlist.email.button': 'Join Waitlist',
        'waitlist.success.title': 'You\'re on the list!',
        'waitlist.success.subtitle': 'We\'ll send you updates and early access when we launch.',
        'waitlist.benefits.early': 'Early Access',
        'waitlist.benefits.free': 'Free to Join',
        'waitlist.benefits.shape': 'Shape the Product',
        'waitlist.features.title': 'Main Features',
        'waitlist.features.subtitle': 'Powerful tools for software architects, tech leads and engineering teams',
        'waitlist.feature.editor.title': 'Markdown Editor + Diagrams',
        'waitlist.feature.editor.desc': 'Collaborative editor with integrated diagram support and rich architectural documentation',
        'waitlist.feature.erd.title': 'Advanced ER Diagrams',
        'waitlist.feature.erd.desc': 'Create entity-relationship diagrams with custom ReactFlow and intelligent interactions',
        'waitlist.feature.workflow.title': 'Workflow Diagrams',
        'waitlist.feature.workflow.desc': 'Visualize process flows and architectural decisions with C4, Mermaid and more',
        'waitlist.feature.ai.title': 'Contextual AI (RAG)',
        'waitlist.feature.ai.desc': 'ChatGPT-style chat that answers about your architectural decisions, ADRs, RFCs and project history',
        'waitlist.feature.search.title': 'Smart Global Search',
        'waitlist.feature.search.desc': 'Find any architectural information with semantic search based on embeddings',
        'waitlist.feature.workspace.title': 'Modular Workspaces',
        'waitlist.feature.workspace.desc': 'Organize projects with modular structure',
        'waitlist.audience.title': 'Ideal for those who value architectural governance',
        'waitlist.audience.subtitle': 'Platform designed for professionals and companies that need to document and maintain architectural decisions',
        'waitlist.audience.architects': 'Software Architects',
        'waitlist.audience.architects_desc': 'Centralize and version your technical decisions with AI',
        'waitlist.audience.leads': 'Tech Leads',
        'waitlist.audience.leads_desc': 'Maintain living and accessible documentation for the team',
        'waitlist.audience.teams': 'Engineering Teams',
        'waitlist.audience.teams_desc': 'Access architectural context and decision history quickly',
        'waitlist.benefits.title': 'Why Join Early Access?',
        'waitlist.benefits.subtitle': 'Be a pioneer in the evolution of architectural documentation',
        'waitlist.benefit.early.title': 'Exclusive Access',
        'waitlist.benefit.early.desc': 'Be the first to use our RAG platform for architecture before public launch',
        'waitlist.benefit.shape.title': 'Influence Development',
        'waitlist.benefit.shape.desc': 'Your feedback will shape the platform\'s features and experience',
        'waitlist.benefit.free.title': 'Free Beta',
        'waitlist.benefit.free.desc': 'Complete access during beta period at no cost for early adopters',
        'waitlist.suggestions.title': 'Share Your Needs',
        'waitlist.suggestions.subtitle': 'Tell us about your current challenges with architectural documentation and governance',
        'waitlist.suggestions.label': 'What challenges do you face in documenting your architecture?',
        'waitlist.suggestions.placeholder': 'E.g.: Difficulty keeping ADRs updated, lack of visibility of architectural decisions, need to query change history...',
        'waitlist.suggestions.button': 'Send Feedback',
        'waitlist.suggestions.success': 'Thank you!',
        'waitlist.suggestions.success_desc': 'Your feedback will help us prioritize features',
        'waitlist.cta.title': 'Ready to Revolutionize Your Architectural Governance?',
        'waitlist.cta.subtitle': 'Join architects and tech leads waiting for the new era of intelligent architectural documentation',
        'waitlist.cta.button': 'Secure Early Access',
        'waitlist.footer.tagline': 'Document, visualize and talk with your architecture',
        'waitlist.toast.email_required': 'Email required',
        'waitlist.toast.email_required_desc': 'Please enter your email address',
        'waitlist.toast.welcome': 'Welcome to the waitlist!',
        'waitlist.toast.welcome_desc': 'We\'ll notify you when early access is available',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('pt');

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
